export const countries: any = {
  "+1": {name: 'United States', dial_code: '+1', emoji: '🇺🇸', code: 'US'},
  "+7": {name: 'Russia', dial_code: '+7', emoji: '🇷🇺', code: 'RU'},
  "+20": {name: 'Egypt', dial_code: '+20', emoji: '🇪🇬', code: 'EG'},
  "+27": {name: 'South Africa', dial_code: '+27', emoji: '🇿🇦', code: 'ZA'},
  "+30": {name: 'Greece', dial_code: '+30', emoji: '🇬🇷', code: 'GR'},
  "+31": {name: 'Netherlands', dial_code: '+31', emoji: '🇳🇱', code: 'NL'},
  "+32": {name: 'Belgium', dial_code: '+32', emoji: '🇧🇪', code: 'BE'},
  "+33": {name: 'France', dial_code: '+33', emoji: '🇫🇷', code: 'FR'},
  "+34": {name: 'Spain', dial_code: '+34', emoji: '🇪🇸', code: 'ES'},
  "+36": {name: 'Hungary', dial_code: '+36', emoji: '🇭🇺', code: 'HU'},
  "+39": {name: 'Italy', dial_code: '+39', emoji: '🇮🇹', code: 'IT'},
  "+40": {name: 'Romania', dial_code: '+40', emoji: '🇷🇴', code: 'RO'},
  "+41": {name: 'Switzerland', dial_code: '+41', emoji: '🇨🇭', code: 'CH'},
  "+43": {name: 'Austria', dial_code: '+43', emoji: '🇦🇹', code: 'AT'},
  "+44": {name: 'United Kingdom', dial_code: '+44', emoji: '🇬🇧', code: 'GB'},
  "+45": {name: 'Denmark', dial_code: '+45', emoji: '🇩🇰', code: 'DK'},
  "+46": {name: 'Sweden', dial_code: '+46', emoji: '🇸🇪', code: 'SE'},
  "+47": {name: 'Norway', dial_code: '+47', emoji: '🇳🇴', code: 'NO'},
  "+48": {name: 'Poland', dial_code: '+48', emoji: '🇵🇱', code: 'PL'},
  "+49": {name: 'Germany', dial_code: '+49', emoji: '🇩🇪', code: 'DE'},
  "+51": {name: 'Peru', dial_code: '+51', emoji: '🇵🇪', code: 'PE'},
  "+52": {name: 'Mexico', dial_code: '+52', emoji: '🇲🇽', code: 'MX'},
  "+53": {name: 'Cuba', dial_code: '+53', emoji: '🇨🇺', code: 'CU'},
  "+54": {name: 'Argentina', dial_code: '+54', emoji: '🇦🇷', code: 'AR'},
  "+55": {name: 'Brazil', dial_code: '+55', emoji: '🇧🇷', code: 'BR'},
  "+56": {name: 'Chile', dial_code: '+56', emoji: '🇨🇱', code: 'CL'},
  "+57": {name: 'Colombia', dial_code: '+57', emoji: '🇨🇴', code: 'CO'},
  "+58": {name: 'Venezuela, Bolivarian Republic of Venezuela', dial_code: '+58', emoji: '🇻🇪', code: 'VE'},
  "+60": {name: 'Malaysia', dial_code: '+60', emoji: '🇲🇾', code: 'MY'},
  "+61": {name: 'Australia', dial_code: '+61', emoji: '🇦🇺', code: 'AU'},
  // "+61": {name: 'Cocos (Keeling) Islands', dial_code: '+61', emoji: '🇨🇨', code: 'CC'},
  "+62": {name: 'Indonesia', dial_code: '+62', emoji: '🇮🇩', code: 'ID'},
  "+63": {name: 'Philippines', dial_code: '+63', emoji: '🇵🇭', code: 'PH'},
  "+64": {name: 'New Zealand', dial_code: '+64', emoji: '🇳🇿', code: 'NZ'},
  "+65": {name: 'Singapore', dial_code: '+65', emoji: '🇸🇬', code: 'SG'},
  "+66": {name: 'Thailand', dial_code: '+66', emoji: '🇹🇭', code: 'TH'},
  "+77": {name: 'Kazakhstan', dial_code: '+77', emoji: '🇰🇿', code: 'KZ'},
  "+81": {name: 'Japan', dial_code: '+81', emoji: '🇯🇵', code: 'JP'},
  "+82": {name: 'Korea, Republic of South Korea', dial_code: '+82', emoji: '🇰🇷', code: 'KR'},
  "+84": {name: 'Vietnam', dial_code: '+84', emoji: '🇻🇳', code: 'VN'},
  "+86": {name: 'China', dial_code: '+86', emoji: '🇨🇳', code: 'CN'},
  "+90": {name: 'Turkey', dial_code: '+90', emoji: '🇹🇷', code: 'TR'},
  "+91": {name: 'India', dial_code: '+91', emoji: '🇮🇳', code: 'IN'},
  "+92": {name: 'Pakistan', dial_code: '+92', emoji: '🇵🇰', code: 'PK'},
  "+93": {name: 'Afghanistan', dial_code: '+93', emoji: '🇦🇫', code: 'AF'},
  "+94": {name: 'Sri Lanka', dial_code: '+94', emoji: '🇱🇰', code: 'LK'},
  "+95": {name: 'Myanmar', dial_code: '+95', emoji: '🇲🇲', code: 'MM'},
  "+98": {name: 'Iran, Islamic Republic of Persian Gulf', dial_code: '+98', emoji: '🇮🇷', code: 'IR'},
  "+211": {name: 'South Sudan', dial_code: '+211', emoji: '🇸🇸', code: 'SS'},
  "+212": {name: 'Morocco', dial_code: '+212', emoji: '🇲🇦', code: 'MA'},
  "+213": {name: 'Algeria', dial_code: '+213', emoji: '🇩🇿', code: 'DZ'},
  "+216": {name: 'Tunisia', dial_code: '+216', emoji: '🇹🇳', code: 'TN'},
  "+218": {name: 'Libyan Arab Jamahiriya', dial_code: '+218', emoji: '🇱🇾', code: 'LY'},
  "+220": {name: 'Gambia', dial_code: '+220', emoji: '🇬🇲', code: 'GM'},
  "+221": {name: 'Senegal', dial_code: '+221', emoji: '🇸🇳', code: 'SN'},
  "+222": {name: 'Mauritania', dial_code: '+222', emoji: '🇲🇷', code: 'MR'},
  "+223": {name: 'Mali', dial_code: '+223', emoji: '🇲🇱', code: 'ML'},
  "+224": {name: 'Guinea', dial_code: '+224', emoji: '🇬🇳', code: 'GN'},
  "+225": {name: "Cote d'Ivoire", dial_code: '+225', emoji: '🇨🇮', code: 'CI'},
  "+226": {name: 'Burkina Faso', dial_code: '+226', emoji: '🇧🇫', code: 'BF'},
  "+227": {name: 'Niger', dial_code: '+227', emoji: '🇳🇪', code: 'NE'},
  "+228": {name: 'Togo', dial_code: '+228', emoji: '🇹🇬', code: 'TG'},
  "+229": {name: 'Benin', dial_code: '+229', emoji: '🇧🇯', code: 'BJ'},
  "+230": {name: 'Mauritius', dial_code: '+230', emoji: '🇲🇺', code: 'MU'},
  "+231": {name: 'Liberia', dial_code: '+231', emoji: '🇱🇷', code: 'LR'},
  "+232": {name: 'Sierra Leone', dial_code: '+232', emoji: '🇸🇱', code: 'SL'},
  "+233": {name: 'Ghana', dial_code: '+233', emoji: '🇬🇭', code: 'GH'},
  "+234": {name: 'Nigeria', dial_code: '+234', emoji: '🇳🇬', code: 'NG'},
  "+235": {name: 'Chad', dial_code: '+235', emoji: '🇹🇩', code: 'TD'},
  "+236": {name: 'Central African Republic', dial_code: '+236', emoji: '🇨🇫', code: 'CF'},
  "+237": {name: 'Cameroon', dial_code: '+237', emoji: '🇨🇲', code: 'CM'},
  "+238": {name: 'Cape Verde', dial_code: '+238', emoji: '🇨🇻', code: 'CV'},
  "+239": {name: 'Sao Tome and Principe', dial_code: '+239', emoji: '🇸🇹', code: 'ST'},
  "+240": {name: 'Equatorial Guinea', dial_code: '+240', emoji: '🇬🇶', code: 'GQ'},
  "+241": {name: 'Gabon', dial_code: '+241', emoji: '🇬🇦', code: 'GA'},
  "+242": {name: 'Congo', dial_code: '+242', emoji: '🇨🇬', code: 'CG'},
  "+243": {name: 'Congo, The Democratic Republic of the Congo', dial_code: '+243', emoji: '🇨🇩', code: 'CD'},
  "+244": {name: 'Angola', dial_code: '+244', emoji: '🇦🇴', code: 'AO'},
  "+245": {name: 'Guinea-Bissau', dial_code: '+245', emoji: '🇬🇼', code: 'GW'},
  "+246": {name: 'British Indian Ocean Territory', dial_code: '+246', emoji: '🇮🇴', code: 'IO'},
  "+248": {name: 'Seychelles', dial_code: '+248', emoji: '🇸🇨', code: 'SC'},
  "+249": {name: 'Sudan', dial_code: '+249', emoji: '🇸🇩', code: 'SD'},
  "+250": {name: 'Rwanda', dial_code: '+250', emoji: '🇷🇼', code: 'RW'},
  "+251": {name: 'Ethiopia', dial_code: '+251', emoji: '🇪🇹', code: 'ET'},
  "+252": {name: 'Somalia', dial_code: '+252', emoji: '🇸🇴', code: 'SO'},
  "+253": {name: 'Djibouti', dial_code: '+253', emoji: '🇩🇯', code: 'DJ'},
  "+254": {name: 'Kenya', dial_code: '+254', emoji: '🇰🇪', code: 'KE'},
  "+255": {name: 'Tanzania, United Republic of Tanzania', dial_code: '+255', emoji: '🇹🇿', code: 'TZ'},
  "+256": {name: 'Uganda', dial_code: '+256', emoji: '🇺🇬', code: 'UG'},
  "+257": {name: 'Burundi', dial_code: '+257', emoji: '🇧🇮', code: 'BI'},
  "+258": {name: 'Mozambique', dial_code: '+258', emoji: '🇲🇿', code: 'MZ'},
  "+260": {name: 'Zambia', dial_code: '+260', emoji: '🇿🇲', code: 'ZM'},
  "+261": {name: 'Madagascar', dial_code: '+261', emoji: '🇲🇬', code: 'MG'},
  "+262": {name: 'Reunion', dial_code: '+262', emoji: '🇷🇪', code: 'RE'},
  "+263": {name: 'Zimbabwe', dial_code: '+263', emoji: '🇿🇼', code: 'ZW'},
  "+264": {name: 'Namibia', emoji: '🇳🇦', dial_code: '+264', code: 'NA'},
  "+265": {name: 'Malawi', dial_code: '+265', emoji: '🇲🇼', code: 'MW'},
  "+266": {name: 'Lesotho', dial_code: '+266', emoji: '🇱🇸', code: 'LS'},
  "+267": {name: 'Botswana', dial_code: '+267', emoji: '🇧🇼', code: 'BW'},
  "+268": {name: 'Swaziland', dial_code: '+268', emoji: '🇸🇿', code: 'SZ'},
  "+269": {name: 'Comoros', dial_code: '+269', emoji: '🇰🇲', code: 'KM'},
  "+290": {name: 'Saint Helena, Ascension and Tristan Da Cunha', dial_code: '+290', emoji: '🇸🇭', code: 'SH'},
  "+291": {name: 'Eritrea', dial_code: '+291', emoji: '🇪🇷', code: 'ER'},
  "+297": {name: 'Aruba', dial_code: '+297', emoji: '🇦🇼', code: 'AW'},
  "+298": {name: 'Faroe Islands', dial_code: '+298', emoji: '🇫🇴', code: 'FO'},
  "+299": {name: 'Greenland', dial_code: '+299', emoji: '🇬🇱', code: 'GL'},
  "+345": {name: 'Cayman Islands', dial_code: '+345', emoji: '🇰🇾', code: 'KY'},
  "+350": {name: 'Gibraltar', dial_code: '+350', emoji: '🇬🇮', code: 'GI'},
  "+351": {name: 'Portugal', dial_code: '+351', emoji: '🇵🇹', code: 'PT'},
  "+352": {name: 'Luxembourg', dial_code: '+352', emoji: '🇱🇺', code: 'LU'},
  "+353": {name: 'Ireland', dial_code: '+353', emoji: '🇮🇪', code: 'IE'},
  "+354": {name: 'Iceland', dial_code: '+354', emoji: '🇮🇸', code: 'IS'},
  "+355": {name: 'Albania', dial_code: '+355', emoji: '🇦🇱', code: 'AL'},
  "+356": {name: 'Malta', dial_code: '+356', emoji: '🇲🇹', code: 'MT'},
  "+357": {name: 'Cyprus', dial_code: '+357', emoji: '🇨🇾', code: 'CY'},
  "+358": {name: 'Finland', dial_code: '+358', emoji: '🇫🇮', code: 'FI'},
  "+359": {name: 'Bulgaria', dial_code: '+359', emoji: '🇧🇬', code: 'BG'},
  "+370": {name: 'Lithuania', dial_code: '+370', emoji: '🇱🇹', code: 'LT'},
  "+371": {name: 'Latvia', dial_code: '+371', emoji: '🇱🇻', code: 'LV'},
  "+372": {name: 'Estonia', dial_code: '+372', emoji: '🇪🇪', code: 'EE'},
  "+373": {name: 'Moldova', dial_code: '+373', emoji: '🇲🇩', code: 'MD'},
  "+374": {name: 'Armenia', dial_code: '+374', emoji: '🇦🇲', code: 'AM'},
  "+375": {name: 'Belarus', dial_code: '+375', emoji: '🇧🇾', code: 'BY'},
  "+376": {name: 'Andorra', dial_code: '+376', emoji: '🇦🇩', code: 'AD'},
  "+377": {name: 'Monaco', dial_code: '+377', emoji: '🇲🇨', code: 'MC'},
  "+378": {name: 'San Marino', dial_code: '+378', emoji: '🇸🇲', code: 'SM'},
  "+379": {name: 'Holy See (Vatican City State)', dial_code: '+379', emoji: '🇻🇦', code: 'VA'},
  "+380": {name: 'Ukraine', dial_code: '+380', emoji: '🇺🇦', code: 'UA'},
  "+381": {name: 'Serbia', dial_code: '+381', emoji: '🇷🇸', code: 'RS'},
  "+382": {name: 'Montenegro', dial_code: '+382', emoji: '🇲🇪', code: 'ME'},
  "+385": {name: 'Croatia', dial_code: '+385', emoji: '🇭🇷', code: 'HR'},
  "+386": {name: 'Slovenia', dial_code: '+386', emoji: '🇸🇮', code: 'SI'},
  "+387": {name: 'Bosnia and Herzegovina', dial_code: '+387', emoji: '🇧🇦', code: 'BA'},
  "+389": {name: 'Macedonia', dial_code: '+389', emoji: '🇲🇰', code: 'MK'},
  "+420": {name: 'Czech Republic', dial_code: '+420', emoji: '🇨🇿', code: 'CZ'},
  "+421": {name: 'Slovakia', dial_code: '+421', emoji: '🇸🇰', code: 'SK'},
  "+423": {name: 'Liechtenstein', dial_code: '+423', emoji: '🇱🇮', code: 'LI'},
  "+500": {name: 'South Georgia and the South Sandwich Islands', dial_code: '+500', emoji: '🇬🇸', code: 'GS'},
  "+501": {name: 'Belize', dial_code: '+501', emoji: '🇧🇿', code: 'BZ'},
  "+502": {name: 'Guatemala', dial_code: '+502', emoji: '🇬🇹', code: 'GT'},
  "+503": {name: 'El Salvador', dial_code: '+503', emoji: '🇸🇻', code: 'SV'},
  "+504": {name: 'Honduras', dial_code: '+504', emoji: '🇭🇳', code: 'HN'},
  "+505": {name: 'Nicaragua', dial_code: '+505', emoji: '🇳🇮', code: 'NI'},
  "+506": {name: 'Costa Rica', dial_code: '+506', emoji: '🇨🇷', code: 'CR'},
  "+507": {name: 'Panama', dial_code: '+507', emoji: '🇵🇦', code: 'PA'},
  "+508": {name: 'Saint Pierre and Miquelon', dial_code: '+508', emoji: '🇵🇲', code: 'PM'},
  "+509": {name: 'Haiti', dial_code: '+509', emoji: '🇭🇹', code: 'HT'},
  "+590": {name: 'Saint Martin', dial_code: '+590', emoji: '🇲🇫', code: 'MF'},
  "+591": {name: 'Bolivia, Plurinational State of', dial_code: '+591', emoji: '🇧🇴', code: 'BO'},
  "+593": {name: 'Ecuador', dial_code: '+593', emoji: '🇪🇨', code: 'EC'},
  "+594": {name: 'French Guiana', dial_code: '+594', emoji: '🇬🇫', code: 'GF'},
  "+595": {name: 'Paraguay', dial_code: '+595', emoji: '🇵🇾', code: 'PY'},
  "+596": {name: 'Martinique', dial_code: '+596', emoji: '🇲🇶', code: 'MQ'},
  "+597": {name: 'Suriname', dial_code: '+597', emoji: '🇸🇷', code: 'SR'},
  "+598": {name: 'Uruguay', dial_code: '+598', emoji: '🇺🇾', code: 'UY'},
  "+599": {name: 'Netherlands Antilles', dial_code: '+599', emoji: '🇧🇶', code: 'AN'},
  "+670": {name: 'Timor-Leste', dial_code: '+670', emoji: '🇹🇱', code: 'TL'},
  "+672": {name: 'Norfolk Island', dial_code: '+672', emoji: '🇳🇫', code: 'NF'},
  "+673": {name: 'Brunei Darussalam', dial_code: '+673', emoji: '🇧🇳', code: 'BN'},
  "+674": {name: 'Nauru', dial_code: '+674', emoji: '🇳🇷', code: 'NR'},
  "+675": {name: 'Papua New Guinea', dial_code: '+675', emoji: '🇵🇬', code: 'PG'},
  "+676": {name: 'Tonga', dial_code: '+676', emoji: '🇹🇴', code: 'TO'},
  "+677": {name: 'Solomon Islands', dial_code: '+677', emoji: '🇸🇧', code: 'SB'},
  "+678": {name: 'Vanuatu', dial_code: '+678', emoji: '🇻🇺', code: 'VU'},
  "+679": {name: 'Fiji', dial_code: '+679', emoji: '🇫🇯', code: 'FJ'},
  "+680": {name: 'Palau', dial_code: '+680', emoji: '🇵🇼', code: 'PW'},
  "+681": {name: 'Wallis and Futuna', dial_code: '+681', emoji: '🇼🇫', code: 'WF'},
  "+682": {name: 'Cook Islands', dial_code: '+682', emoji: '🇨🇰', code: 'CK'},
  "+683": {name: 'Niue', dial_code: '+683', emoji: '🇳🇺', code: 'NU'},
  "+685": {name: 'Samoa', dial_code: '+685', emoji: '🇼🇸', code: 'WS'},
  "+686": {name: 'Kiribati', dial_code: '+686', emoji: '🇰🇮', code: 'KI'},
  "+687": {name: 'New Caledonia', dial_code: '+687', emoji: '🇳🇨', code: 'NC'},
  "+688": {name: 'Tuvalu', dial_code: '+688', emoji: '🇹🇻', code: 'TV'},
  "+689": {name: 'French Polynesia', dial_code: '+689', emoji: '🇵🇫', code: 'PF'},
  "+690": {name: 'Tokelau', dial_code: '+690', emoji: '🇹🇰', code: 'TK'},
  "+691": {name: 'Micronesia, Federated States of Micronesia', dial_code: '+691', emoji: '🇫🇲', code: 'FM'},
  "+692": {name: 'Marshall Islands', dial_code: '+692', emoji: '🇲🇭', code: 'MH'},
  "+850": {name: "Korea, Democratic People's Republic of Korea", dial_code: '+850', emoji: '🇰🇵', code: 'KP'},
  "+852": {name: 'Hong Kong', dial_code: '+852', emoji: '🇭🇰', code: 'HK'},
  "+853": {name: 'Macao', dial_code: '+853', emoji: '🇲🇴', code: 'MO'},
  "+855": {name: 'Cambodia', dial_code: '+855', emoji: '🇰🇭', code: 'KH'},
  "+856": {name: 'Laos', dial_code: '+856', emoji: '🇱🇦', code: 'LA'},
  "+872": {name: 'Pitcairn', dial_code: '+872', emoji: '🇵🇳', code: 'PN'},
  "+880": {name: 'Bangladesh', dial_code: '+880', emoji: '🇧🇩', code: 'BD'},
  "+886": {name: 'Taiwan', dial_code: '+886', emoji: '🇹🇼', code: 'TW'},
  "+960": {name: 'Maldives', dial_code: '+960', emoji: '🇲🇻', code: 'MV'},
  "+961": {name: 'Lebanon', dial_code: '+961', emoji: '🇱🇧', code: 'LB'},
  "+962": {name: 'Jordan', dial_code: '+962', emoji: '🇯🇴', code: 'JO'},
  "+963": {name: 'Syrian Arab Republic', dial_code: '+963', emoji: '🇸🇾', code: 'SY'},
  "+964": {name: 'Iraq', dial_code: '+964', emoji: '🇮🇷', code: 'IQ'},
  "+965": {name: 'Kuwait', dial_code: '+965', emoji: '🇰🇼', code: 'KW'},
  "+966": {name: 'Saudi Arabia', dial_code: '+966', emoji: '🇸🇦', code: 'SA'},
  "+967": {name: 'Yemen', dial_code: '+967', emoji: '🇾🇪', code: 'YE'},
  "+968": {name: 'Oman', dial_code: '+968', emoji: '🇴🇲', code: 'OM'},
  "+970": {name: 'Palestinian Territory, Occupied', dial_code: '+970', emoji: '🇵🇸', code: 'PS'},
  "+971": {name: 'United Arab Emirates', dial_code: '+971', emoji: '🇦🇪', code: 'AE'},
  "+972": {name: 'Israel', dial_code: '+972', emoji: '🇮🇱', code: 'IL'},
  "+973": {name: 'Bahrain', dial_code: '+973', emoji: '🇧🇭', code: 'BH'},
  "+974": {name: 'Qatar', dial_code: '+974', emoji: '🇶🇦', code: 'QA'},
  "+975": {name: 'Bhutan', dial_code: '+975', emoji: '🇧🇹', code: 'BT'},
  "+976": {name: 'Mongolia', dial_code: '+976', emoji: '🇲🇳', code: 'MN'},
  "+977": {name: 'Nepal', dial_code: '+977', emoji: '🇳🇵', code: 'NP'},
  "+992": {name: 'Tajikistan', dial_code: '+992', emoji: '🇹🇯', code: 'TJ'},
  "+993": {name: 'Turkmenistan', dial_code: '+993', emoji: '🇹🇲', code: 'TM'},
  "+994": {name: 'Azerbaijan', dial_code: '+994', emoji: '🇦🇿', code: 'AZ'},
  "+995": {name: 'Georgia', dial_code: '+995', emoji: '🇬🇪', code: 'GE'},
  "+996": {name: 'Kyrgyzstan', dial_code: '+996', emoji: '🇰🇬', code: 'KG'},
  "+997": {name: 'Kazakhstan', dial_code: '+77', emoji: '🇰🇿', code: 'KZ'},
  "+998": {name: 'Uzbekistan', dial_code: '+998', emoji: '🇺🇿', code: 'UZ'},
  "+1242": {name: 'Bahamas', dial_code: '+1242', emoji: '🇧🇸', code: 'BS'},
  "+1246": {name: 'Barbados', dial_code: '+1246', emoji: '🇧🇧', code: 'BB'},
  "+1264": {name: 'Anguilla', dial_code: '+1264', emoji: '🇦🇮', code: 'AI'},
  "+1268": {name: 'Antigua and Barbuda', dial_code: '+1268', emoji: '🇦🇬', code: 'AG'},
  "+1284": {name: 'Virgin Islands, British', dial_code: '+1284', emoji: '🇻🇬', code: 'VG'},
  "+1340": {name: 'Virgin Islands, U.S.', dial_code: '+1340', emoji: '🇻🇮', code: 'VI'},
  "+1441": {name: 'Bermuda', dial_code: '+1441', emoji: '🇧🇲', code: 'BM'},
  "+1473": {name: 'Grenada', dial_code: '+1473', emoji: '🇬🇩', code: 'GD'},
  "+1649": {name: 'Turks and Caicos Islands', dial_code: '+1649', emoji: '🇹🇨', code: 'TC'},
  "+1664": {name: 'Montserrat', dial_code: '+1664', emoji: '🇲🇸', code: 'MS'},
  "+1670": {name: 'Northern Mariana Islands', dial_code: '+1670', emoji: '🇲🇵', code: 'MP'},
  "+1671": {name: 'Guam', dial_code: '+1671', emoji: '🇬🇺', code: 'GU'},
  "+1684": {name: 'AmericanSamoa', dial_code: '+1684', emoji: '🇦🇸', code: 'AS'},
  "+1758": {name: 'Saint Lucia', dial_code: '+1758', emoji: '🇱🇨', code: 'LC'},
  "+1767": {name: 'Dominica', dial_code: '+1767', emoji: '🇩🇲', code: 'DM'},
  "+1784": {name: 'Saint Vincent and the Grenadines', dial_code: '+1784', emoji: '🇻🇨', code: 'VC'},
  "+1849": {name: 'Dominican Republic', dial_code: '+1849', emoji: '🇩🇴', code: 'DO'},
  "+1868": {name: 'Trinidad and Tobago', dial_code: '+1868', emoji: '🇹🇹', code: 'TT'},
  "+1869": {name: 'Saint Kitts and Nevis', dial_code: '+1869', emoji: '🇰🇳', code: 'KN'},
  "+1876": {name: 'Jamaica', dial_code: '+1876', emoji: '🇯🇲', code: 'JM'},
  "+1939": {name: 'Puerto Rico', dial_code: '+1939', emoji: '🇵🇷', code: 'PR'},
  "+88": {name: 'International', dial_code: '+88', emoji: '🇺🇳', code: 'UN'},
  "+388": {name: 'EU +388', dial_code: '+388', emoji: '🇪🇺', code: 'EU'},
}